# Generated by Django 4.0.5 on 2022-07-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatuser_rooms_im_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='chatuser',
            name='rooms_im_in',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='rooms_im_in',
            field=models.ManyToManyField(blank=True, null=True, to='chat.chatroom'),
        ),
    ]
