# Generated by Django 4.0.5 on 2022-07-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_directchat_remove_chatuser_rooms_im_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='rooms_im_in',
            field=models.ManyToManyField(blank=True, to='chat.chatroom'),
        ),
    ]
