# Generated by Django 4.0.5 on 2022-07-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatuser_rooms_im_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='last_used_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_room', to='chat.chatroom'),
        ),
    ]
